version: '3.8'

services:
  backend:
    build: .
    ports:
      - "9000:8000"
    env_file:
      - .env  # Sử dụng file .env.docker cho Docker
    environment:
      # Database
      - DATABASE_URL=${DATABASE_URL}
      
      # Email Configuration
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
      - EMAILS_FROM_NAME=${EMAILS_FROM_NAME}
      
      # JWT Configuration
      # - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-11520}
      - VERIFICATION_CODE_EXPIRE_MINUTES=${VERIFICATION_CODE_EXPIRE_MINUTES:-30}
      
      # Cloudinary Configuration
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      
      # Gemini AI Configuration
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_REWRITE_API_KEY=${GEMINI_REWRITE_API_KEY}
      - GEMINI_MODEL_NAME=${GEMINI_MODEL_NAME}
      
      # External API URLs
      - DEEPFAKE_API_URL=${DEEPFAKE_API_URL}
      - TTS_API_URL=${TTS_API_URL}
      - FAKELIP_API_URL=${FAKELIP_API_URL}
      
      # CORS
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","https://lecture-video-generate-fe.vercel.app","http://36.50.135.165:3000"]
    volumes:
      - static_data:/app/static
      - uploads_data:/app/uploads
      - output_data:/app/output
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  static_data:
  uploads_data:
  output_data:
  mysql_data:
